services:
    LightSaml\Idp\Builder\Profile\WebBrowserSso\Idp\SsoIdpReceiveAuthnRequestProfileBuilder:
        arguments:
            - "@lightsaml.container.build"

    SchoolIT\LightSamlIdpBundle\Builder\Profile\WebBrowserSso\Idp\SsoIdpSendResponseProfileBuilderFactory:
        arguments:
          - "@lightsaml.container.build"