services:
  lightsaml.idp.request_listener:
    class: SchoolIT\LightSamlIdpBundle\EventListener\SamlRequestListener
    arguments:
      - "@lightsaml.idp.request_storage"
    tags:
      - { name: kernel.event_subscriber }
    public: true

  lightsaml.idp.request_storage:
    class: SchoolIT\LightSamlIdpBundle\RequestStorage\SessionRequestStorage
    arguments:
      - "@request_stack"
    public: true