services:
  SchoolIT\LightSamlIdpBundle\EventListener\SamlRequestListener:
      autowire: true
      autoconfigure: true

  SchoolIT\LightSamlIdpBundle\RequestStorage\RequestStorageInterface:
      alias: SchoolIT\LightSamlIdpBundle\RequestStorage\SessionRequestStorage

  SchoolIT\LightSamlIdpBundle\RequestStorage\SessionRequestStorage:
      autowire: true