services:
  SchulIT\LightSamlIdpBundle\EventListener\SamlRequestListener:
      autowire: true
      autoconfigure: true

  SchulIT\LightSamlIdpBundle\RequestStorage\RequestStorageInterface:
      alias: SchulIT\LightSamlIdpBundle\RequestStorage\SessionRequestStorage

  SchulIT\LightSamlIdpBundle\RequestStorage\SessionRequestStorage:
      autowire: true